{
 "title": "IDP Microservices Overview",
 "tags": [
  "idp",
  "microservices"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests per second (by endpoint)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(auth_requests_total[1m])) by (endpoint)",
     "legendFormat": "auth - {{endpoint}}"
    },
    {
     "expr": "sum(rate(catalog_requests_total[1m])) by (endpoint)",
     "legendFormat": "catalog - {{endpoint}}"
    },
    {
     "expr": "sum(rate(order_requests_total[1m])) by (endpoint)",
     "legendFormat": "order - {{endpoint}}"
    }
   ]
  },
  {
   "title": "Total Orders Placed",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "orders_placed_total" }
   ]
  },
  {
   "title": "Total Failed Orders",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(orders_failed_total)" }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(catalog_request_duration_seconds_bucket[5m])) by (le, endpoint))",
     "legendFormat": "catalog p95 - {{endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(order_request_duration_seconds_bucket[5m])) by (le, endpoint))",
     "legendFormat": "order p95 - {{endpoint}}"
    }
   ]
  }
 ]
}